services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --port 6777
    ports:
      - "6777:6777"
  gateway:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    ports:
      - 5872:5872
