services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6777:6379"
  gateway:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 5872:5872
